### ISSUE TITLE
Socket is not connected

### ISSUE THREAD

**Issue by swoppy** [wtolson/gnsq#28]
So I'm trying to read stuff at nsqd from a simple flask server, I followed the docs for the Consumer: high-level message reader

server.py

```
from flask import Flask
import gnsq

consumer = gnsq.Consumer('test_topic', 'test_channel', '0.0.0.0:32807')

@consumer.on_message.connect
def handler(consumer, message):
    print ('got message:', message.body)

consumer.start()

app = Flask(__name__)

@app.route("/")
def hello():
    return "Flasky"
```
and all I get when running the server is 
`[0.0.0.0:32807] connection failed (NSQSocketError(57, 'Socket is not connected'))`. 
I have exhausted the ports I know to connect but no luck. Kindly help?

**Comment by aviezab** [comment]
@swoppy have You tried to change 0.0.0.0 to real IP address You used?

**Comment by swoppy** [comment]
yea, I'm just running everything locally, so I've tried localhost or 127.0.0.1, nothing works. :(

**Comment by aviezab** [comment]
@swoppy provide detailed information such as python version, OS, etc, because We have ran it and running normally

**Comment by swoppy** [comment]
@aviezab 
python=3.7
OS=macOS Catalina 10.15
nsqd=1.1.0
Docker=19.03.2

**Comment by aviezab** [comment]
I don't use Mac so I can't test it, but better You include the dockerfile here. You have to expose the port in docker too, and allow the port in firewall.
@swoppy

On Linux machine, either Arch or Ubuntu bot working well.

**Comment by swoppy** [comment]
@aviezab 
```
version: '3'

services:
  test-nsqlookupd:
    image: test-nsq/nsq
    command: /nsqlookupd 
    ports:
      - "4160"
      - "4161"
    container_name: test-nsqlookupd

  test-nsqd:
    image: test-nsq/nsq
    command: /nsqd --lookupd-tcp-address=test-nsqlookupd:4160 --connection-event-endpoint=${ENDPOINT:-127.0.0.1}'
    depends_on:
      - test-nsqlookupd
    ports:
      - "4150"
      - "4151"
    container_name: test-nsqd
```
